using System;
using System.Reflection;

class Program
{
    static void Main(string[] args)
    {
        /*******************************************

            [EVENT] <Lecture>
            E3 1995

            1995 Electronics Entertainment Expo

            May 11, 1995

            1:00 PM
            
            1201 S Figueroa St, Los Angeles, CA

            Speaker: Steve Race

            50000 max capacity

        ********************************************/
        // create address
        Address address0 = new Address("1201 S Figueroa St", "Los Angeles", "CA");  

        // create Lecture event
        Lecture lecture = new Lecture("E3 1995", "1995 Electronics Entertainment Expo", "May 11, 1995", "1:00 PM", address0.FormatAddress(), "Steve Race", 50000);

        /********************************************

            [EVENT] <Reception>
            Pong Demonstration

            Nolan Bushnell and Al Alcorn present "Pong"
            
            November 29, 1972

            10:00 AM

            157 West El Camino Real, Sunnyvale, CA

            Dear [Recipient's Name],

            I hope this message finds you well. I am excited to invite
            you to Andy Capp's Tavern in Sunnyvale, California, to
            experience something truly revolutionary in the world of
            entertainment. Recently, a brand-new game called "Pong" has
            been introduced at the tavern, and it’s creating quite a
            buzz. Pong is a simple yet captivating electronic game that
            simulates table tennis. I believe you would thoroughly enjoy
            trying it out. It promises to be an evening of fun, friends, 
            and a first-hand experience with this groundbreaking game. 
            Looking forward to seeing you there!

            Best regards,
            [Your Name]

            (Generated by OpenAI ChatGPT)
        ********************************************/
        // store large string
        string email = 

            @"
            Dear [Recipient's Name],

            I hope this message finds you well. I am excited to invite
            you to Andy Capp's Tavern in Sunnyvale, California, to
            experience something truly revolutionary in the world of
            entertainment. Recently, a brand-new game called 'Pong' has
            been introduced at the tavern, and it’s creating quite a
            buzz. Pong is a simple yet captivating electronic game that
            simulates table tennis. I believe you would thoroughly enjoy
            trying it out.It promises to be an evening of fun, friends, 
            and a first-hand experience with this groundbreaking game.
            Looking forward to seeing you there!

            Best regards,
            [Your Name]

            (Generated by OpenAI ChatGPT)
        ";

        // create address
        Address address1 = new Address("157 West El Camino Real", "Sunnyvale", "CA");

        // create reception event
        Reception reception = new Reception("Pong Demonstration", "Nolan Bushnell and Al Alcorn present 'Pong'", "November 29, 1972", "10:00 AM", address1.FormatAddress(), email);

        /********************************************

            [EVENT] <Outdoor>
            Fly a Kite Day

            Fly a key infused kite with Benjamin Franklin

            June 10, 1752

            7:00 PM

            317 Chestnut St, Philadelphia, PA

            Weather Conditions: Very Poor

        ********************************************/

        // create address
        Address address2 = new Address("317 Chestnut St", "Philadelphia", "PA");

        // create reception event
        Outdoor outdoor = new Outdoor("Fly a Kite Day", "Fly a key infused kite with Benjamin Franklin", "June 10, 1752", "7:00 PM", address2.FormatAddress(), "Very Poor");

        // display standard information
        Console.WriteLine("Standard Details:\n");
        lecture.DisplayStandardDetails();
        Console.WriteLine("\n\n");
        reception.DisplayStandardDetails();
        Console.WriteLine("\n\n");
        outdoor.DisplayStandardDetails();

        // display full information
        Console.WriteLine("\n\n\n\nFull Details");
        lecture.DisplayFullDetails();
        Console.WriteLine();
        reception.DisplayFullDetails();
        Console.WriteLine();
        outdoor.DisplayFullDetails();
        
        // display short information
        Console.WriteLine("\n\nShort Details");
        lecture.DisplayShortDescription();
        Console.WriteLine();
        reception.DisplayShortDescription();
        Console.WriteLine();
        outdoor.DisplayShortDescription();
        Console.WriteLine("\n\nEnd of Line.");
    }
}